baseurl = "https://blog.leejay.top/"
languageCode = "en-us"
theme = "terminal"
paginate = 10
[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  favicon="/img/favicon.png"
[languages]
  [languages.en]
    title = "Keep Improving"
    subtitle = "ğŸˆğŸˆğŸˆ"
    keywords = ""
    copyright = "è‹ICPå¤‡18050258å·-1"
    menuMore = "æ›´å¤š"
    writtenBy = "Written by"
    readMore = "é˜…è¯»æ›´å¤š"
    readOtherPosts = "å…¶ä»–æ–‡ç« "
    NewerPosts = "ä¸Šä¸€é¡µ"
    OlderPosts = "ä¸‹ä¸€é¡µ"
    minuteReadingTime = "é˜…è¯»æ—¶é—´"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "HelloWorld"
      logoHomeLink = "https://blog.leejay.top/"
      # logoHomeLink = "/"

    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "tags"
    #     name = "Tags"
    #     url = "/tags"
    #   [[languages.en.menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     url = "/categories"
# å†…åµŒhtmlé…ç½®       
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[permalinks]
  posts = '/:slug'