baseurl = "https://www.leejay.top"
languageCode = "zh-Hans"
theme = "friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false
[languages]
  [languages.en]
    title = "Aurora"
    subtitle = "ğŸˆğŸˆğŸˆ"
    keywords = ""
    copyright = "è‹ICPå¤‡18050258å·-1"
    menuMore = "æ›´å¤š"
    writtenBy = "Written by"
    readMore = "é˜…è¯»æ›´å¤š"
    readOtherPosts = "å…¶ä»–æ–‡ç« "
    newerPosts = "ä¸Šä¸€é¡µ"
    olderPosts = "ä¸‹ä¸€é¡µ"
    minuteReadingTime = "é˜…è¯»æ—¶é—´"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Aurora"
      logoHomeLink = "https://www.leejay.top"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
     
